name = "Dice"
uuid = "94eeadfc-1ba6-40b7-9ed8-dee71557d525"
authors = ["Guy Van den Broeck <guyvdb@gmail.com>"]
version = "0.1.0"

[deps]
CUDD = "345a2cc7-28d8-58b2-abdf-cff77ea7d7f1"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
DirectedAcyclicGraphs = "1e6dae5e-d6e2-422d-9af3-452e7a3785ee"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
IRTools = "7869d1d1-7146-5819-86e3-90919afe41df"
IfElse = "615f187c-cbe4-4ef1-ba3b-2fcf58d6d173"
Jive = "ba5e3d4b-8524-549f-bc71-e76ad9e9deed"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
TikzGraphs = "b4f28e30-c73f-5eaf-a395-8a9db949a742"
TikzPictures = "37f6aa50-8035-52d0-81c2-5a1d08754b2d"

[compat]
CUDD = "0.2.2"
DirectedAcyclicGraphs = "0.1.1"
IRTools = "0.4"
IfElse = "0.1"
Jive = "0.2"
MacroTools = "0.5"
julia = "1.7"
