name: Unit Tests 

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: 
  pull_request:
  push:
  workflow_dispatch:

env:
  JIVE_PROCS: 1

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@latest
        with:
          version: 1.10.5
          
      - name: Install Latex Dependencies
        run:
          sudo apt update && sudo apt install -y pdf2svg texlive-latex-base texlive-binaries texlive-latex-extra texlive-luatex

      - name: Install SymPy
        run: 
          pip3 install sympy

      - name: Instantiate Packages
        run: |
          julia --project -e 'using Pkg; Pkg.instantiate(); Pkg.add(url="https://github.com/PoorvaGarg/IRTools.jl", rev="loop-break-patch"); Pkg.add("SymPy"); Pkg.build();'

      - name: Unit Tests
        run:
          julia --project --check-bounds=yes --depwarn=yes -e 'import Pkg; Pkg.test(; coverage=true)'
      
      - name: Codecov Upload
        run:
          julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder());'
